# Site settings
title: Barnsley Council Design Guide
email: danielroddis@barnsley.gov.uk
description: > # this means to ignore newlines until "baseurl:"
  Design and brand guidelines for Barnsley Council
baseurl: "/design-guide" # the subpath of your site, e.g. /blog/
url: "https://barnsleycouncil.github.io" # the base hostname & protocol for your site
twitter_username: barnsleycouncil
github_username:  thedanroddis
sass:
    sass_dir: _sass
    style: :compressed

# Build settings
markdown: kramdown
collections:
    about:
        output: true
    components:
        output: true
    foundations:
        output: true
    journeys:
        output: true
    principles:
        output: true
    objects:
        output: true
    templates:
        output: true